config/routes.rb
Rails.application.routes.draw do

  get '/create_user', to:'users#new'
  get '/login', to:'sessions#new'
  post '/login', to:'sessions#create'
  delete '/logout', to:'sessions#destroy'

  root 'chat_rooms#index'
  resources :chats
  resources :chat_rooms
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :chat_room
  belongs_to :user
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  has_many :chats
end

app/models/user.rb
class User < ApplicationRecord
  has_many :chats

  def encrypt(token)
    Digest::SHA256.hexdigest(token.to_s)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def authenticate
    if User.find_by(id: session[:user_id]).nil?
      # まだログインしていない
      return redirect_to '/login'
    end
  end

  def current_user
    User.find(session[:user_id])
  end



end

app/controllers/chat_rooms_controller.rb
class ChatRoomsController < ApplicationController
  before_action :authenticate

  def new
    @chat_room = ChatRoom.new
    @user = current_user
  end

  def index
    @chat_rooms = ChatRoom.all
    @user = current_user
  end

  def show
    @chat_room = ChatRoom.find(params[:id])
    @chats = @chat_room.chats
    @user = current_user
  end


  def create
    @chat_room = ChatRoom.new(chat_room_params)
    @chat_room.save!
    redirect_to @chat_room
    @user = current_user
  end

private
  def chat_room_params
    params.require(:chat_room).permit(:chat_name, :chat_room_id)
  end

end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :authenticate

  def new
    @chat = Chat.new
  end

  def edit
  end

  def index
    @chats = Chat.all
  end

  def show
    @chat = Chat.find(params[:id])
    redirect_to action: 'index'
  end

  def create
    chat_room = ChatRoom.find(params[:chat_room_id])

    @chat = Chat.new(chat_params)
    @chat.chat_room = chat_room
    @chat.user = current_user
    @chat.save!

    redirect_to chat_room_path(chat_room)
  end

  private
    def chat_params
      params.require(:chat).permit(:content)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :set_user, only: [:create]
  def new
  end

  def create
    # authenticate

    if authenticate(@user, params[:session][:pass]) then
      puts params[:session][:pass]
      session[:user_id] = @user.id
      return redirect_to '/'
    else
      flash.now[:danger] = 'login失敗'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    return redirect_to '/login'
  end

  private

  def set_user
    @user = User.find_by!(name: session_params[:name])
    rescue
      render action: 'new'
  end

  def session_params
    params.require(:session).permit(:name, :password_digest)
  end

  def authenticate(user, password)
    user.password_digest == user.encrypt(password)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def index
    @users = User.all
  end

  def create
    @user = User.new(user_params)
    @user.password_digest = @user.encrypt(user_params[:password_digest])
    @user.save!
    redirect_to @user
  end

  private
    def user_params
      params.require(:user).permit(:name,:password_digest)
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chat_rooms_helper.rb
module ChatRoomsHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chat_rooms/index.html.erb
<div class="page-header">
<h1>ChatRoom一覧</h1>
</div>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>room_id</th>
      <th>room_name</th>
    </tr>
  </thead>
<% @chat_rooms.each do |chat_room| %>
  <tbody>
    <td><%= chat_room.id %></td>
    <td><%= chat_room.chat_name %></td>
    <td><%= link_to 'in', chat_room_path(chat_room), class: 'btn btn-success'%></td>
  </tbody>
<% end %>
</table>

app/views/chat_rooms/new.html.erb
<h1>CreateRoom</h1>
<%= form_for :chat_room, url: chat_rooms_path do |f| %>
<p>
  新しい部屋を作成します。
</p>
<p>
  room_name:<%= f.text_field :chat_name %><%= f.submit %>
</p>
<% end %>

app/views/chat_rooms/show.html.erb
<h1><%= @chat_room.chat_name %></h1>
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>user_name</th>
      <th>content</th>
    </tr>
  </thead>
  <tbody>
    <% @chats.each do |chat| %>
    <tr>
      <td><%= chat.user.name %></td>
      <td><%= chat.content %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<hr>
<%= form_for Chat.new, url: chats_path + "?chat_room_id=#{@chat_room.id}"  do |f| %>
<div class="input-group">
  <span class="input-group-addon">コメント</span>
  <%=  f.text_field :content,type: 'text',class: 'form-control' %>
  <span class="input-group-btn">
  <%= f.submit"送信",class: 'btn btn-primary' %>
</span>
</div>
<% end %>
<hr>
<%= link_to '一覧に戻る', chat_rooms_path %>

app/views/layouts/_footer.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container-fluid">
    <div class="navbar-text">
      <a><%= link_to '新しい部屋を作成する', new_chat_room_path %></a>
      <a><%= link_to 'logout', logout_path, method: :delete %></a>
    </div>
  </div>
</nav>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbarmenu">
        <span class="sr-only">This is chat</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">
        ChatRoom
      </a>
    </div>
    <ul class="collapse navbar-collapse list-horizontal" id="navbarmenu">
      <li class="dropdown navbar-text navbar-right">
        <ul class="dropdown-toggle" data-toggle="dropdown">
          <span class="glyphicon glyphicon-list" aria-hidden="true"></span>
        </ul>
        <ul class="dropdown-menu">
          <li role="presentation"><%= link_to '新しい部屋を作成する', new_chat_room_path %></li>
          <li role="presentation" class="divider"></li>
          <li role="presentation"><%= link_to 'logout', logout_path, method: :delete %></li>
        </ul>
      </li>
      <li class="navbar-text navbar-right">
        ようこそ<%= @user.name %>さん
      </li>
    </ul>
  </div>
</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chat</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if User.find_by(id: session[:user_id]).nil? %>
      <div class="container bg-info">
    <% else %>
      <%= render 'layouts/header' %>
      <div class="container">
    <% end %>
      <%= yield %>
    </div>
    <% if User.find_by(id: session[:user_id]).nil? %>
      <% else %>
      <%= render 'layouts/footer' %>
    <% end %>
  </body>
</html>

app/views/users/new.html.erb
<div class="jumbotron">
  <h1>CreateUser</h1>
</div>
<%= form_for @user, url: users_path do |f| %>
<form class="form-horizontal">
  <div class="form-group">
    <label class="col-sm-2 control-label">name:</label>
    <%= f.text_field :name,class: 'col-sm-5', placeholder: 'name' %><br>
  </div>
  <div class="form-group">
    <label class="col-sm-2 control-label">pass:</label>
    <%= f.text_field :password_digest,class: 'col-sm-5', placeholder: 'password' %><br>
  </div>
  <div class="form-group">
    <%= f.submit"CreateUser",class: 'col-sm-offset-2 col-sm-2 btn btn-primary' %><br>
  </div>
</form>
<% end %>

app/views/users/show.html.erb
<h1>新しいuserを作成しました</h1>
<p>
  user_id:<%= @user.id %><br>
  name:<%= @user.name %>
  <%= link_to 'room一覧へと戻る', chat_rooms_path %>
</p>